### ISSUE TITLE
Would it be possible to adapt addon for 3.4.0 calssic to work on 3.3.5? 

### ISSUE THREAD

**Issue by IgorDrgonec** [ManneN1/BigDebuffs-WotLK#8]
It has many features like buffs/debuffs on nameplates.

**Comment by ManneN1** [comment]
Unfortunately the 3.3.5 client works extremely poorly with any kind of nameplate animations, also there are no nameplate units so the nameplate to aura mapping (and their length/duration) will always be a guess (outside of arena).

For this reason these aspects of modern BigDebuffs will not be backported.

Note: Yes, I am aware animations can be done top-to-bottom, without flickering - but since that is not how the AddOn works in retail I will not be implementing it. If you are interested in auras on nameplates I recommend https://github.com/bkader/PlateBuffs_WoTLK, although it is very CPU hungry.
